# Site Settings
title:               Pailab Blog
tagline:             Pailab Offical Blog
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Pailab"
  email:             "info@pailab.net"
  twitter:           "pailabnet"
  instagram:         "pailab"
  github:            "pailab"
  linkedin:          "pailab"
navigation:
- title: Hakkımızda
  url: /about
- title: Yazılar
  url: /writing
- title: İletisim
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
