
# Site Settings
title:               Pailab Blog
tagline:             Pailab Offical Blog
description:		Pailab ekibinin yazmış olduğu blog yazılarının listelendiği web sayfası
rss:			
  url:                "http://blog.pailab.net/feed.xml"
baseurl:            #"/Lagrange"
url:                #"http://blog.pailab.net"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Pailab"
  email:             "info@pailab.net"
  twitter:           "pailabnet"
  instagram:         "pailabnet"
  github:            "pailab"
  linkedin:          "pailab"
navigation:
- title: Hakkımızda
  url: /about
- title: Yazılar
  url: /writing
- title: İletisim
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                
  - jekyll-paginate
