# Site Settings
title:               Pailab
tagline:             Tecrübe blogu
description:
baseurl:            #"/Lagrange"
url:                "http://blog.pailab.net"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Pailab"
  email:             "info@pailab.net"
  twitter:           "pailabnet"
  instagram:         "pailabnet"
  github:            "pailab"
  facebook:          "pailabnet"
  linkedin:          "pailabnet"
navigation:
- title: Hakkımızda
  url: /about
- title: Yazılar
  url: /writing
- title: İletişim
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
